<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5b2a9f6e61bd01ec4aa37b9cd8bb5cbf
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5b2a9f6e61bd01ec4aa37b9cd8bb5cbf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5b2a9f6e61bd01ec4aa37b9cd8bb5cbf::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
